# Site
name: "World traveler wooji"
title: "World traveler wooji"
description: "world traveler woojidream blog"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /mylife
google_analytics: 'UA-157553034-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  wooji:
    name: wooji
    display_name: wooji
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: woojidream@gmail.com
    web: https://www.woojimarket.com
    facebook: https://www.facebook.com/woojimarket
    description: "world traveler wooji"
  john lenon:
    name: John lenon
    display_name: John lenon
    avatar: 'assets/images/avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: woojimarket@gmail.com
    web: https://www.facebook.com/woojimarket
    facebook: https://www.facebook.com/woojimarket
    description: "husband of wooji"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 12
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
